name: Repositort events
on: [push, pull_request, issues]
jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: list all files before checkout
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v4

