name: checkout actions
on: [push]
jobs :
  checkout-actions-job:
    runs-on: ubuntu-latest
    steps:
      - name: list all files before checkout
        run: |
          ls -a 
          pwd
      - uses: actions/checkout@v4
      - name: list all files after checkout
        run: |
          ls -a 
          pwd

