name: Expressions and context
on:
  push:
    branches:
      - "feat/*"
jobs:
  Expressions:
        runs-on: ubuntu-latest
        steps:
          - name: Expressions
            id:  expressions
            run: |
                echo "*************Github*****************"
                echo "${{ toJson(github) }}"
                echo "*************Github*****************"
                echo "${{ toJson(job) }}"
                echo "*************Github*****************"
                echo "${{ toJson(secrets) }}"
                echo "*************Github*****************"
                echo "${{ toJson(steps) }}"
                echo "*************Github*****************"
                echo "${{ toJson(runner) }}"