name : First Wrorkflow
on: [push]


jobs :
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello world
        run: echo "Hello World"
      - name: Multi line shell commands
        run: |
            node -v
            npm -v
  second-job:
    runs-on: macos-latest
    steps:
      -name: View SW Version
      run : sw_vers

  dependent=job:
    runs-on: windows-latest
    needs : [run-shell-commands]
    steps:
      - name : echo a string
        run : Write-Output "a windos a string"
      - name : Error Step
        run : doesnotexcit
