name: var and secrets
on:
  push:
    branches:
      - "feat/*"

jobs:
  var-and-secrets:
    runs-on: ${{ vars.RUNNER }}
    env:
      runner: ${{ vars.RUNNER }}
      ENV_LEVEL_VAR : ${{ vars.ENV_LEVEL_VAR }}
      ACTIONS_RUNNER_DEBUG : ${{ vars.ACTIONS_RUNNER_DEBUG }}
    steps:
      - name: pass secrets
        run: echo ${{ secrets.PASS_SECRET }}
      - name: pass secrets with if condition
        if: env.ACTIONS_RUNNER_DEBUG == 'false'
        run:
          echo "secret is running in debug mode"
          echo var.ENV_LEVEL_VAR




