name: var and secrets
on:
  push:
    branches:
      - "feat/*"

jobs:
    var-and-secrets:
        runs-on: ubuntu-latest
        steps:
        - name: pass secrets
          run: echo ${{ secrets.PASS_SECRET }}
        - name: staging level var
          run: echo ${{ vars.RUNNER }}
