name: var and secrets
on:
  push:
    branches:
      - "feat/*"

jobs:
  decrypt-file:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - uses: actions/checkout@v4
      - name: decrypt file
        env:
          pass: ${{ secrets.API_KEY }}
        run: |
          mkdir $HOME/secrets
          openssl aes-256-cbc -d -in enc.json.enc -out $HOME/secrets/dec.json -pass pass:$pass
          echo $pass
      - name: View encrypted file
        run : cat $HOME/secrets/dec.json

  var-and-secrets:
    runs-on: ${{ vars.RUNNER }}
    environment: PROD
    env:
      runner: ${{ vars.RUNNER }}
      ENV_LEVEL_VAR : ${{ vars.ENV_LEVEL_VAR }}
      ACTIONS_RUNNER_DEBUG : ${{ vars.ACTIONS_RUNNER_DEBUG }}
    steps:
      - name: pass secrets
        run: echo ${{ secrets.PASS_SECRET }}
      - name: pass secrets with if condition
        if: env.ACTIONS_RUNNER_DEBUG == 'false'
        run : |
          echo "secret is running in debug mode"
          echo $ENV_LEVEL_VAR 




