name: var and secrets
on:
  push:
    branches:
      - "feat/*"

jobs:
    var-and-secrets:
        runs-on: ubuntu-latest
        steps:
        - name: echo ${{ secrets.PASS_SECRET }}
          run: echo "Hello World"
